# Use a base image oficial do Python
FROM python:3.12.4-slim

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie o arquivo de requisitos e instale as dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copie todo o código fonte da sua aplicação para o diretório de trabalho
COPY . .

# Comando para executar a aplicação quando o contêiner for iniciado
CMD ["python", "run.py"]
